version: 2

run:
  timeout: 10m
  skip-dirs:
    - vendor
    - third_party

formatters:
  enable:
    - gofmt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - bodyclose
    - gosec
    - prealloc
    - unconvert
    - unused
    - cyclop

linters-settings:
  cyclop:
    max-complexity: 20
  
  gosec:
    excludes:
      - G115  # Integer overflow - intentional for PostgreSQL wire protocol compatibility
    
  gocritic:
    # Which checks should be enabled
    enabled-checks:
      - ruleguard
      - truncateCmp

    # Which checks should be disabled
    disabled-checks:
      - captLocal
      - assignOp
      - paramTypeCombine
      - importShadow
      - commentFormatting

    # Enable multiple checks by tags
    enabled-tags:
      - performance
      - diagnostic
      - opinionated
    disabled-tags:
      - experimental
    settings:
      hugeParam:
        # size in bytes that makes the warning trigger
        sizeThreshold: 1000
      rangeExprCopy:
        # size in bytes that makes the warning trigger
        sizeThreshold: 512
        # whether to check test functions
        skipTestFuncs: true
      truncateCmp:
        # whether to skip int/uint/uintptr types
        skipArchDependent: true
      underef:
        # whether to skip (*x).method() calls where x is a pointer receiver
        skipRecvDeref: true

  govet:
    disable:
      - deepequalerrors
      - fieldalignment
      - shadow
      - unsafeptr
      
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should be"
    - linters:
        - errcheck
      text: "not checked"
    - linters:
        - staticcheck
      text: "SA(1019|1029|5011)"
  exclude-dirs:
    - hack