version: "2"

run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - bodyclose
    - gosec
    - prealloc
    - unconvert
    - unused
    - cyclop

linters-settings:
  cyclop:
    max-complexity: 30

  gosec:
    excludes:
      - G115  # Integer overflow - intentional for PostgreSQL wire protocol compatibility

  gocritic:
    enabled-checks:
      - ruleguard
      - truncateCmp

    disabled-checks:
      - captLocal
      - assignOp
      - paramTypeCombine
      - importShadow
      - commentFormatting

    enabled-tags:
      - performance
      - diagnostic
      - opinionated
    disabled-tags:
      - experimental

  govet:
    disable:
      - deepequalerrors
      - fieldalignment
      - shadow
      - unsafeptr

  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-dirs-use-default: false
  exclude-dirs:
    - vendor
    - third_party
    - hack