run:
  timeout: 10m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - gocritic
    - bodyclose
    - gosec
    - prealloc
    - unconvert
    - unused

linters-settings:
  govet:
    disable:
      - deepequalerrors
      - fieldalignment
      - shadow
      - unsafeptr

  gocritic:
    enabled-checks:
      - ruleguard
      - truncateCmp
    disabled-checks:
      - captLocal
      - assignOp
      - paramTypeCombine
      - importShadow
      - commentFormatting

  gosec:
    excludes:
      - G115  # Integer overflow - intentional for PostgreSQL wire protocol compatibility

  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-dirs:
    - vendor
    - third_party
    - hack
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019|SA1029|SA5011"