version: "2"

run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - gocritic
    - gosec
    - prealloc
    - unconvert
    - misspell
    - goconst

  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
        - stdmethods

    gocritic:
      enabled-checks:
        - ruleguard
        - truncateCmp
      disabled-checks:
        - captLocal
        - assignOp
        - commentFormatting

    gosec:
      excludes:
        - G115  # Integer overflow - intentional for PostgreSQL wire protocol
        - G104  # Unhandled errors - using errcheck instead
        - G402  # TLS version too low/disabled  - intentional for PostgreSQL

    goconst:
      min-len: 3
      min-occurrences: 3

  exclusions:
    paths:
      - vendor
      - third_party
      - hack
      - lib/fed/packets
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - linters:
          - staticcheck
        text: "SA1019|SA1029|SA5011"
