general:
  host: 0.0.0.0
  port: 6432
  enable_prometheus_exporter: true
  prometheus_exporter_port: 9090
  connect_timeout: 5000
  healthcheck_timeout: 1000
  healthcheck_delay: 30000
  shutdown_timeout: 60000
  ban_time: 60
  autoreload: false
  admin_username: postgres
  admin_password: postgres
pools:
  postgres:
    pool_mode: session
    default_role: primary
    query_parser_enabled: true
    primary_reads_enabled: true
    sharding_function: pg_bigint_hash
    users:
      - username: postgres
        password: password
        role: writer
        pool_size: 20
        statement_timeout: 0
    shards:
      - pool_size: 5
        statement_timeout: 0
        database: postgres
        servers:
          - host: db
            port: 5432
            role: primary
            username: postgres
            password: example
  regression:
    pool_mode: session
    default_role: primary
    query_parser_enabled: true
    primary_reads_enabled: true
    sharding_function: pg_bigint_hash
    users:
      - username: postgres
        password: password
        role: writer
        pool_size: 20
        statement_timeout: 0
    shards:
      - pool_size: 5
        statement_timeout: 0
        database: regression
        servers:
          - host: db
            port: 5432
            role: primary
            username: postgres
            password: ENV$PGGAT_DB_PASS
