general:
  host: 0.0.0.0
  port: 6432
  enable_prometheus_exporter: true
  prometheus_exporter_port: 9090
  connect_timeout: 5000
  healthcheck_timeout: 1000
  healthcheck_delay: 30000
  shutdown_timeout: 60000
  ban_time: 60
  autoreload: false
  admin_username: postgres
  admin_password: postgres
pools:
  simple_db:
    pool_mode: session
    default_role: primary
    query_parser_enabled: true
    primary_reads_enabled: true
    sharding_function: pg_bigint_hash
    users:
      - username: postgres
        password: postgres
        role: reader
        pool_size: 5
        statement_timeout: 0
      - username: postgres
        password: password
        role: writer
        pool_size: 20
        statement_timeout: 0
    shards:
      - pool_size: 5
        statement_timeout: 0
        database: postgres
        servers:
          - host: localhost
            port: 5432
            role: primary
            username: postgres
            password: postgres
          - host: localhost
            role: replica
            port: 5432
            username: postgres
            password: postgres
  sharded:
    pool_mode: transaction
    default_role: any
    query_parser_enabled: true
    primary_reads_enabled: true
    sharding_function: pg_bigint_hash
    users:
      - username: postgres
        password: postgres
        pool_size: 9
        statement_timeout: 0
      - username: postgres
        password: postgres
        pool_size: 21
        statement_timeout: 15000
    shards:
      - database: postgres
        servers:
          - host: localhost
            port: 5432
            role: primary
            username: postgres
            password: postgres
          - host: localhost
            role: replica
            port: 5432
            username: postgres
            password: postgres
      - database: postgres
        servers:
          - host: localhost
            port: 5432
            role: primary
          - host: localhost
            role: replica
            port: 5432
            username: postgres
            password: postgres
      - database: postgres
        servers:
          - host: localhost
            port: 5432
            role: primary
            username: postgres
            password: postgres
          - host: localhost
            role: replica
            port: 5432
            username: postgres
            password: postgres
