package packets

import "pggat2/lib/zap"

const (
	TypeAuthentication           zap.Type = 'R'
	TypeBackendKeyData           zap.Type = 'K'
	TypeBind                     zap.Type = 'B'
	TypeBindComplete             zap.Type = '2'
	TypeClose                    zap.Type = 'C'
	TypeCloseComplete            zap.Type = '3'
	TypeCommandComplete          zap.Type = 'C'
	TypeCopyData                 zap.Type = 'd'
	TypeCopyDone                 zap.Type = 'c'
	TypeCopyFail                 zap.Type = 'f'
	TypeCopyInResponse           zap.Type = 'G'
	TypeCopyOutResponse          zap.Type = 'H'
	TypeCopyBothResponse         zap.Type = 'W'
	TypeDataRow                  zap.Type = 'D'
	TypeDescribe                 zap.Type = 'D'
	TypeEmptyQueryResponse       zap.Type = 'I'
	TypeErrorResponse            zap.Type = 'E'
	TypeExecute                  zap.Type = 'E'
	TypeFlush                    zap.Type = 'H'
	TypeFunctionCall             zap.Type = 'F'
	TypeFunctionCallResponse     zap.Type = 'V'
	TypeAuthenticationResponse   zap.Type = 'p'
	TypeNegotiateProtocolVersion zap.Type = 'v'
	TypeNoData                   zap.Type = 'n'
	TypeNoticeResponse           zap.Type = 'N'
	TypeNotificationResponse     zap.Type = 'A'
	TypeParameterDescription     zap.Type = 't'
	TypeParameterStatus          zap.Type = 'S'
	TypeParse                    zap.Type = 'P'
	TypeParseComplete            zap.Type = '1'
	TypePortalSuspended          zap.Type = 's'
	TypeQuery                    zap.Type = 'Q'
	TypeReadyForQuery            zap.Type = 'Z'
	TypeRowDescription           zap.Type = 'T'
	TypeSync                     zap.Type = 'S'
	TypeTerminate                zap.Type = 'X'
)
