package packet

type Type byte

const (
	Authentication           Type = 'R'
	BackendKeyData           Type = 'K'
	Bind                     Type = 'B'
	BindComplete             Type = '2'
	Close                    Type = 'C'
	CloseComplete            Type = '3'
	CommandComplete          Type = 'C'
	CopyData                 Type = 'd'
	CopyDone                 Type = 'c'
	CopyFail                 Type = 'f'
	CopyInResponse           Type = 'G'
	CopyOutResponse          Type = 'H'
	CopyBothResponse         Type = 'W'
	DataRow                  Type = 'D'
	Describe                 Type = 'D'
	EmptyQueryResponse       Type = 'I'
	ErrorResponse            Type = 'E'
	Execute                  Type = 'E'
	Flush                    Type = 'H'
	FunctionCall             Type = 'F'
	FunctionCallResponse     Type = 'V'
	AuthenticationResponse   Type = 'p'
	NegotiateProtocolVersion Type = 'v'
	NoData                   Type = 'n'
	NoticeResponse           Type = 'N'
	NotificationResponse     Type = 'A'
	ParameterDescription     Type = 't'
	ParameterStatus          Type = 'S'
	Parse                    Type = 'P'
	ParseComplete            Type = '1'
	PortalSuspended          Type = 's'
	Query                    Type = 'Q'
	ReadyForQuery            Type = 'Z'
	RowDescription           Type = 'T'
	Sync                     Type = 'S'
	Terminate                Type = 'X'
)
